#!/bin/sh
#
# Dynamic Mail Client
#

VERSION="0.1"
COPYRIGHT="Copyleft -- pancake@nopcode.org"

[ -n "${EDITOR}" ] && EDITOR=vim
mkdir -p ~/.dmc/mail
mkdir -p ~/.dmc/tmp
mkdir -p ~/.dmc/acc

function acc_daemon {
  FIFO=~/.dmc/tmp/${NAME}.fifo
  INPUT=~/.dmc/tmp/${NAME}.input
  OUTPUT=~/.dmc/tmp/${NAME}.output

  if [ ${SSL} = 1 ]; then
    NETCMD="openssl s_client -host $HOST -port $POST"
  else
    NETCMD="nc $HOST $PORT"
  fi

  echo "Starting $NAME account daemon..."

  rm -f ${INPUT}
  mkfifo ${INPUT}
#  echo login ${USER} ${PASS} > ${INPUT}
  (while : ; do cat ${INPUT} ; done) | \
    ./dmc-${PROTOCOL} $FIFO 2> ${OUTPUT} | $NETCMD > $FIFO
  rm -f ${INPUT}
}

function start_account_daemons {
  i=0
  for a in ~/.dmc/acc/* ; do
    ( source $a ; acc_daemon ) &
    i=$(($i+1))
  done
  if [ "$i" = 0 ]; then
    echo "No accounts defined in ~/.dmc/acc"
    exit 1
  fi
}

function print_account_template {
    echo "NAME='test'"
    echo "SSL=0"
    echo "PROTOCOL='pop3,imap4'"
    echo "HOST=serverhost.com"
    echo "PORT=110"
    echo "#SEND=acc-name"
    echo "SEND=|msmtp"
    echo "USER='username'"
    echo "PASS='password'"
}

case "$1" in
"-d"|"--start")
  start_account_daemons
  ;;
"-k"|"--stop")
  for a in ~/.dmc/tmp/*.input ; do
    echo $a
    echo exit > $a
    rm -f ~/.dmc/tmp/$a
  done
  ;;
"-e"|"--edit")
  if [ -n "$2" ]; then
    [ -n "`cat ~/.dmc/acc/$2`" ] && \
      print_account_template "$2" > ~/.dmc/acc/$2
    vim ~/.dmc/acc/$2
    # Remove account if empty
    [ -z "`cat ~/.dmc/acc/$2`" ] && \
      rm ~/.dmc/acc/$2
  else
    echo "Usage: dmc -e [accountname]"
  fi
  ;;
"push")
  ;;
"pull")
  ;;
"-m"|"--mail")
  TO="$2"
  ;;
"-a"|"--addr")
  if [ -n "$2" ]; then
    grep -e "$2" ~/.dmc/addrbook
  else
    ${EDITOR} ~/.dmc/addrbook
  fi
  ;;
"-v"|"--version")
  echo "dmc v${VERSION} ${COPYRIGHT}"
  ;;
"--help"|"-h"|*)
  echo "Usage: dmc [-e acc] [-a addr] [-hvdk]"
  ;;
esac

exit 0
