#!/bin/sh
# dmc - dynamic mail client
# Copyleft 2009 -- pancake <at> nopcode <dot> org
# TODO: rewrite in C

MD=$1
if [ -z "${MD}" ]; then
	echo "Usage: dmc-mdir [Maildir-path]"
	exit 1
fi

dir=""
while : ; do
	read A
	arg0=`echo $A | cut -d ' ' -f 1`
	arg1=`echo $A | cut -d ' ' -f 2-`
	case $arg0 in
	"ls")
		echo "cur $(ls $MD/$dir/cur | wc -l)"
		echo "new $(ls $MD/$dir/new | wc -l)"
		echo "tmp $(ls $MD/$dir/tmp | wc -l)"
		echo "### 1 ls" > /dev/stderr
		;;
	"lsd")
		( cd $MD/$dir ; ls -d .??* | cat )
		echo "### 1 lsd" > /dev/stderr
		;;
	"cat")
		file=$(ls $MD/$dir | head -n $arg1 | tail -n 1)
		if [ -f "$file" ]; then
			cat $file
			echo "### 1 cat" > /dev/stderr
		else
			echo "### 0 cat No such file" > /dev/stderr
		fi
		;;
	"head")
		dmc-hdr : < $(ls $MD/$dir/tmp | head -n $arg1 | tail -n 1)
		echo "### 1 head" > /dev/stderr
		;;
	"rm")
		file=$(ls $MD/$dir | head -n $arg1 | tail -n 1)
		if [ -f "$file" ]; then
			rm -f $file
			echo "### 1 rm" > /dev/stderr
		else
			echo "### 0 rm No such file" > /dev/stderr
		fi
		;;
	"pwd")
		echo $dir
		echo "### 1 pwd" > /dev/stderr
		;;
	"login")
		# ignore
		;;
	"exit")
		exit 0
		;;
	"cd")
		dir=$arg1
		;;
	*)
		echo "Usage: ls lsd cat cd"
		;;
	esac
done
